### PR TITLE
downgrade log level for success log

### PR DESCRIPTION
**Pull request by will-gluwa**
Not sure why this was originally an error log. Assuming by mistake?

### CODE REVIEW

**Review by dcmiddle — DISMISSED** [review]
well c++ TPs were never meant to work so if it does then it's an error ;)
thanks for the fix

**Comment by will-gluwa** [comment]
Fixed the DCO requirement

**Comment by will-gluwa** [comment]
@dcmiddle, think you can get a second reviewer to approve this? Maybe @agunde406 or @peterschwarz?

**Review by agunde406 — APPROVED** [review]

**Review by peterschwarz — APPROVED** [review]

**Comment by agunde406** [comment]
Thanks for the PR

**Pull request merged**
