### PR TITLE
Fix Incorrect Comment about CheckIfValidNamespace

### PR DESCRIPTION
**Pull request by danintel**
s/Checks if an address string/Checks if a namespace string/

Signed-off-by: danintel <daniel.anderson@intel.com>

### CODE REVIEW

**Comment by danintel** [comment]
My comment was not addressed in PR #2, so I am making a new PR here.

**Comment by danintel** [comment]
@EugeneYYY I made the changes you requested.

I also enhanced the exception message to print the invalid length (as is currently done for addresses).

**Comment by dcmiddle** [comment]
@danintel could you please recreate this PR for the c++ sdk repo?
https://github.com/hyperledger/sawtooth-sdk-cxx

**Comment by danintel** [comment]
@dcmiddle Sure, but what is there to recreate? My repo is still there, the PR is still here, and there have been no conflicting merges, let alone merges in the mean time.

**Pull request merged**
